<a href="https://colab.research.google.com/github/hajin0324/DeepLearning/blob/main/MNIST_Classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [88]:
# 케라스에서 MNIST 데이터셋 적재
from tensorflow.keras.datasets import mnist
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

In [89]:
# training data
train_images.shape

(60000, 28, 28)

In [90]:
len(train_labels)

60000

In [91]:
train_labels

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [92]:
# test data
test_images.shape

(10000, 28, 28)

In [93]:
len(test_labels)

10000

In [94]:
test_labels

array([7, 2, 1, ..., 4, 5, 6], dtype=uint8)

In [95]:
# 신경망 구조
from tensorflow import keras
from tensorflow.keras import layers

model = keras.Sequential([
    layers.Dense(512, activation="relu"),
    layers.Dense(10, activation="softmax")
])

**층(layer**)
* 데이터를 위한 필터
* 주어진 문제에 더 의미 있는 표현을 입력된 데이터로부터 추출



In [96]:
# 컴파일 단계
model.compile(optimizer="rmsprop",
              loss = "sparse_categorical_crossentropy",
              metrics=["accuracy"])

훈련 준비를 마치기 위해 컴파일 단계에 포함될 세 가지
* 옵티마이저(optimizer) : 성능을 향상시키기 위해 입력된 데이터를 기반으로 모델을 업데이트하는 메커니즘
* 손실 함수(loss function) : 훈련 데이터에서 모델의 성능을 측정하는 방법으로 모델이 옳은 방향으로 학습될 수 있도록 도와줌
* 훈련과 테스트 과정을 모니터링할 지표 

In [97]:
# 이미지 데이터 준비
train_images = train_images.reshape((60000, 28 * 28))
train_images = train_images.astype("float32") / 255
test_images = test_images.reshape((10000, 28 * 28))
test_images = test_images.astype("float32") / 255

데이터를 모델에 맞는 크기로 바꾸고 모든 값을 0과 1 사이로 스케일 조정  
[0, 255] 사이의 값인 unit8 타입의 (60000, 28, 28) 크기의 배열  
-> 0과 1 사이의 값을 가지는 float32 타입의 (60000, 28* 28) 크기의 배열



In [98]:
# 모델 훈련하기
model.fit(train_images, train_labels, epochs=5, batch_size=128)

Epoch 1/5
469/469 [==============================] - 6s 13ms/step - loss: 0.2645 - accuracy: 0.9240
Epoch 2/5
469/469 [==============================] - 5s 10ms/step - loss: 0.1067 - accuracy: 0.9686
Epoch 3/5
469/469 [==============================] - 5s 10ms/step - loss: 0.0700 - accuracy: 0.9789
Epoch 4/5
469/469 [==============================] - 6s 12ms/step - loss: 0.0507 - accuracy: 0.9849
Epoch 5/5
469/469 [==============================] - 5s 10ms/step - loss: 0.0385 - accuracy: 0.9881


In [99]:
# 모델을 사용하여 예측 만들기
test_digits = test_images[0:10]
predictions = model.predict(test_digits)
predictions[0]

1/1 [==============================] - 0s 62ms/step


array([1.6701525e-08, 4.0448231e-09, 7.6627214e-07, 3.4292108e-05,
       6.0063815e-11, 4.7325251e-08, 8.0824349e-12, 9.9996048e-01,
       5.8569885e-08, 4.2879224e-06], dtype=float32)

인덱스 i에 있는 숫자는 숫자 이미지 test_digits[0]이 클래스 i에 속할 확률

In [100]:
predictions[0].argmax()

7

In [101]:
predictions[0][7]

0.9999605

In [102]:
# 테스트 데이터의 레이블과 맞는지 확인
test_labels[0]

7

In [103]:
# 새로운 데이터에서 모델 평가
test_loss, test_acc = model.evaluate(test_images, test_labels)
print(f"테스트 정확도 : {test_acc}")

313/313 [==============================] - 1s 3ms/step - loss: 0.0613 - accuracy: 0.9816
테스트 정확도 : 0.9815999865531921
