<a href="https://colab.research.google.com/github/hajin0324/DeepLearning/blob/main/MNIST_Classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**케라스에서 MNIST 데이터셋 적재**

In [120]:
from tensorflow.keras.datasets import mnist
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

In [121]:
# training data
train_images.shape

(60000, 28, 28)

In [122]:
len(train_labels)

60000

In [123]:
train_labels

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [124]:
# test data
test_images.shape

(10000, 28, 28)

In [125]:
len(test_labels)

10000

In [126]:
test_labels

array([7, 2, 1, ..., 4, 5, 6], dtype=uint8)

**신경망 구조**

In [127]:
from tensorflow import keras
from tensorflow.keras import layers

model = keras.Sequential([
    layers.Dense(512, activation="relu"),
    layers.Dense(10, activation="softmax")
])

층(layer)
* 데이터를 위한 필터
* 주어진 문제에 더 의미 있는 표현을 입력된 데이터로부터 추출



**컴파일 단계**

In [128]:
model.compile(optimizer="rmsprop",
              loss = "sparse_categorical_crossentropy",
              metrics=["accuracy"])

훈련 준비를 마치기 위해 컴파일 단계에 포함될 세 가지
* 옵티마이저(optimizer) : 성능을 향상시키기 위해 입력된 데이터를 기반으로 모델을 업데이트하는 메커니즘
* 손실 함수(loss function) : 훈련 데이터에서 모델의 성능을 측정하는 방법으로 모델이 옳은 방향으로 학습될 수 있도록 도와줌
* 훈련과 테스트 과정을 모니터링할 지표 

**이미지 데이터 준비**

In [129]:
train_images = train_images.reshape((60000, 28 * 28))
train_images = train_images.astype("float32") / 255
test_images = test_images.reshape((10000, 28 * 28))
test_images = test_images.astype("float32") / 255

데이터를 모델에 맞는 크기로 바꾸고 모든 값을 0과 1 사이로 스케일 조정  
[0, 255] 사이의 값인 unit8 타입의 (60000, 28, 28) 크기의 배열  
-> 0과 1 사이의 값을 가지는 float32 타입의 (60000, 28* 28) 크기의 배열



**모델 훈련하기**

In [130]:
model.fit(train_images, train_labels, epochs=5, batch_size=128)

Epoch 1/5
469/469 [==============================] - 7s 11ms/step - loss: 0.2686 - accuracy: 0.9215
Epoch 2/5
469/469 [==============================] - 5s 10ms/step - loss: 0.1076 - accuracy: 0.9675
Epoch 3/5
469/469 [==============================] - 6s 12ms/step - loss: 0.0711 - accuracy: 0.9788
Epoch 4/5
469/469 [==============================] - 5s 10ms/step - loss: 0.0513 - accuracy: 0.9848
Epoch 5/5
469/469 [==============================] - 5s 10ms/step - loss: 0.0384 - accuracy: 0.9885


**모델을 사용하여 예측 만들기**

In [131]:
test_digits = test_images[0:10]
predictions = model.predict(test_digits)
predictions[0]

1/1 [==============================] - 0s 89ms/step


array([3.8658641e-07, 3.4269146e-08, 2.0618245e-06, 2.4903391e-04,
       6.9504368e-11, 5.8852572e-07, 5.2117733e-12, 9.9973083e-01,
       1.8457416e-06, 1.5235548e-05], dtype=float32)

인덱스 i에 있는 숫자는 숫자 이미지 test_digits[0]이 클래스 i에 속할 확률

In [132]:
predictions[0].argmax()

7

In [133]:
predictions[0][7]

0.9997308

In [134]:
# 테스트 데이터의 레이블과 맞는지 확인
test_labels[0]

7

**새로운 데이터에서 모델 평가**

In [135]:
test_loss, test_acc = model.evaluate(test_images, test_labels)
print(f"테스트 정확도 : {test_acc}")

313/313 [==============================] - 1s 4ms/step - loss: 0.0600 - accuracy: 0.9811
테스트 정확도 : 0.9811000227928162
