<a href="https://colab.research.google.com/github/hajin0324/DeepLearning/blob/main/MNIST_Classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**케라스에서 MNIST 데이터셋 적재**

In [136]:
from tensorflow.keras.datasets import mnist
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

**training data**

In [137]:
# train_images의 차원
train_images.shape

(60000, 28, 28)

In [138]:
# train_labels의 길이
len(train_labels)

60000

In [139]:
# train_labels 출력
train_labels

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

**test data**

In [140]:
# test_images의 차원
test_images.shape

(10000, 28, 28)

In [141]:
# test_labels의 길이
len(test_labels)

10000

In [142]:
# test_labels 출력
test_labels

array([7, 2, 1, ..., 4, 5, 6], dtype=uint8)

**신경망 구조**

In [143]:
from tensorflow import keras
from tensorflow.keras import layers
# from tensorflow.keras.laers import Dense

model = keras.Sequential([
    layers.Dense(512, activation="relu"),
    layers.Dense(10, activation="softmax")
# == tensorflow.keras.layers.Dense(10, activation="softmax")
# == keras.layers.Dense(10, activation="softmax")
# == Dense(10, activation="softmax")
])

층(layer)
* 데이터를 위한 필터
* 주어진 문제에 더 의미 있는 표현을 입력된 데이터로부터 추출   

Sequential : 순차적으로 layer 층을 더해줌  

2개의 Dense층

* relu : 0보다 작으면 0, 0보다 크면 입력 값 그대로 출력
* softmax : 입력받은 값을 0 ~ 1 사이의 값으로 정규화, 출력 값들의 총합 = 1



**컴파일 단계**

In [144]:
model.compile(optimizer="rmsprop",
              loss = "sparse_categorical_crossentropy",
              metrics=["accuracy"])

훈련 준비를 마치기 위해 컴파일 단계에 포함될 세 가지
* 옵티마이저(optimizer) : 성능을 향상시키기 위해 입력된 데이터를 기반으로 모델을 업데이트하는 메커니즘  
rmsprop(Root Mean Sqaure Propagation) : 지수이동평균(Exponential Moving Average)을 활용하여 기울기 업데이트
* 손실 함수(loss function) : 훈련 데이터에서 모델의 성능을 측정하는 방법으로 모델이 옳은 방향으로 학습될 수 있도록 도와줌  
sparse_categorical_crossentropy : one-hot encoding 생략 시
* 훈련과 테스트 과정을 모니터링할 지표

**이미지 데이터 준비**

In [145]:
train_images = train_images.reshape((60000, 28 * 28))
# (60000, 28 * 28) == (60000, -1) == (-1, 28 * 28)
# 28 * 28 size 이미지가 60000개
train_images = train_images.astype("float32") / 255
test_images = test_images.reshape((10000, 28 * 28))
test_images = test_images.astype("float32") / 255

데이터를 모델에 맞는 크기로 바꾸고 모든 값을 0과 1 사이로 스케일 조정  
[0, 255] 사이의 값인 unit8 타입의 (60000, 28, 28) 크기의 배열  
→ 0과 1 사이의 값을 가지는 float32 타입의 (60000, 28* 28) 크기의 배열

**모델 훈련하기**

In [146]:
model.fit(train_images, train_labels, epochs=5, batch_size=128)

Epoch 1/5
469/469 [==============================] - 5s 10ms/step - loss: 0.2650 - accuracy: 0.9236
Epoch 2/5
469/469 [==============================] - 5s 10ms/step - loss: 0.1064 - accuracy: 0.9686
Epoch 3/5
469/469 [==============================] - 6s 12ms/step - loss: 0.0707 - accuracy: 0.9788
Epoch 4/5
469/469 [==============================] - 5s 10ms/step - loss: 0.0507 - accuracy: 0.9849
Epoch 5/5
469/469 [==============================] - 6s 12ms/step - loss: 0.0388 - accuracy: 0.9887


케라스에서는 모델의 fit() 메서드를 호출하여 훈련 데이터에 모델을 학습
* epochs : 전체 트레이닝 셋이 신경망을 통화한 횟수
* batch_size : 전체 training dataset을 작은 그룹으로 나누었을 때 하나의 소그룹에 속하는 데이터 수

**모델을 사용하여 예측 만들기**

In [147]:
test_digits = test_images[0:10]  # 10장의 이미지
predictions = model.predict(test_digits)
predictions[0]

1/1 [==============================] - 0s 54ms/step


array([1.5106618e-08, 2.7941301e-08, 1.8546916e-06, 9.2540977e-05,
       2.9256899e-11, 3.6144183e-08, 2.6461455e-12, 9.9988931e-01,
       5.7069439e-08, 1.6033340e-05], dtype=float32)

인덱스 i에 있는 숫자는 숫자 이미지 test_digits[0]이 클래스 i에 속할 확률

In [148]:
# 여러 개의 수 중에서 가장 큰 값의 인덱스
predictions[0].argmax()

7

In [149]:
# 첫번째 이미지의 인덱스 7의 확률
predictions[0][7] 

0.9998893

In [150]:
# 테스트 데이터의 레이블과 맞는지 확인
test_labels[0]

7

**새로운 데이터에서 모델 평가**

In [151]:
test_loss, test_acc = model.evaluate(test_images, test_labels)
print(f"테스트 정확도 : {test_acc}")

313/313 [==============================] - 1s 3ms/step - loss: 0.0679 - accuracy: 0.9791
테스트 정확도 : 0.9790999889373779
